# These are supported funding model platforms
github: [eddiedover] # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: "eddiedover" # Replace with a single Patreon username
ko_fi: eddiedover
